name: Build Official Signed APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # تغییر سیستم‌عامل سرور به نسخه پایدارتر ۲۰.۰۴ جهت هماهنگی با کامپایلرهای قدیمی پایتون
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip python3-pip \
            autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 \
            cmake libffi-dev libssl-dev

      - name: Install buildozer
        run: |
          pip install --upgrade pip setuptools wheel
          pip install "cython<3.0.0" buildozer

      - name: Decode Keystore
        run: |
          if [ -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "ERROR: KEYSTORE_BASE64 secret is not set!"
            exit 1
          fi
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > tasbih-releser.keystore

      - name: Cache buildozer
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            .buildozer
          key: ${{ runner.os }}-buildozer-clang-fixed-v99
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Build Official Release APK
        run: |
          rm -rf bin/
          buildozer android release --auto-accept-licenses
        env:
          BUILDOZER_WARN_ON_ROOT: 0
          # پچ حیاتی: مسدود کردن فلگ خراب کامپایلر پایتون در محیط اوبونتو
          # این دو خط زیر دقیقا آپشن مخرب را در زمان کامپایل خنثی می‌کنند
          CFLAGS: "-Wno-error=unused-command-line-argument"
          CXXFLAGS: "-Wno-error=unused-command-line-argument"
